services:
  - type: web
    name: beherbest
    env: python
    python:
      version: 3.10.12
    buildCommand: |
      # Install Python and build dependencies
      python -m pip install --upgrade pip setuptools wheel
      
      # Install core dependencies directly
      pip install django>=5.1.6 gunicorn==21.2.0 psycopg2-binary==2.9.9 whitenoise==6.6.0
      
      # Install the package in development mode
      pip install -e .
      
      # Collect static files
      python manage.py collectstatic --noinput
      
      # Run migrations
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: DJANGO_SETTINGS_MODULE
        value: "myproject.settings"
      - key: PYTHONPATH
        value: "/opt/render/project/src/Website"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: DEBUG
        value: "False"  # Set to False in production
      - key: DISABLE_COLLECTSTATIC
        value: "0"  # Enable collectstatic
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: ALLOWED_HOSTS
        value: "beherbest.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://beherbest.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
      - key: DATABASE_URL
        fromDatabase:
          name: beherbest-db
          property: connectionString
