# Generated by Django 4.2.20 on 2025-04-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_googledrivefolder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mega_file_link', models.URLField(max_length=500, unique=True)),
                ('membership_tier', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('diamond', 'Diamond')], default='regular', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Membership Access',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('diamond', 'Diamond')], default='regular', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.membershiptier')),
            ],
        ),
        migrations.RemoveField(
            model_name='googledrivevideo',
            name='folder',
        ),
        migrations.AlterModelOptions(
            name='videoprogress',
            options={'ordering': ['-last_watched']},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='videostreamsession',
            name='drive_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Video streaming URL', unique=True),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='current_time',
            field=models.FloatField(default=0, help_text='Current time in seconds'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='progress',
            field=models.FloatField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.video'),
        ),
        migrations.DeleteModel(
            name='FolderAccess',
        ),
        migrations.DeleteModel(
            name='GoogleDriveVideo',
        ),
        migrations.AddField(
            model_name='membershipaccess',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.membershiptier'),
        ),
        migrations.AddField(
            model_name='membershipaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='video',
            name='drive_folder',
        ),
        migrations.RemoveField(
            model_name='video',
            name='membership_tier',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.membershiptier'),
        ),
        migrations.AddField(
            model_name='video',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.membershiptier'),
        ),
        migrations.DeleteModel(
            name='GoogleDriveFolder',
        ),
    ]
