# Generated by Django 4.2.20 on 2025-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_megavideo_membershipaccess_membershiptier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='mega_link',
            field=models.URLField(blank=True, help_text='MEGA video link', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='secure_playback',
            field=models.BooleanField(default=True, help_text='Enable token-based secure playback'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
