# Generated by Django 4.2.20 on 2025-04-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_video_duration_ms_video_mega_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megavideo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='megavideo',
            name='mega_file_link',
            field=models.URLField(help_text='MEGA video link', max_length=500),
        ),
        migrations.AlterField(
            model_name='megavideo',
            name='membership_tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('diamond', 'Diamond')], default='regular', max_length=20),
        ),
    ]
