# Generated by Django 4.2.20 on 2025-04-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_megavideo_is_free_video_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.membershiptier'),
        ),
    ]
