# Generated by Django 4.2.20 on 2025-04-16 15:46

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_video_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='megavideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail image (max 2MB, JPG/PNG)', null=True, upload_to='mega_video_thumbnails/', validators=[myapp.models.validate_file_size, myapp.models.validate_file_extension]),
        ),
    ]
