# Generated by Django 4.2.20 on 2025-05-03 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_megavideo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_tier', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('diamond', 'Diamond')], max_length=10)),
                ('reason', models.TextField()),
                ('screenshot', models.ImageField(upload_to='upgrade_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_upgrades', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Upgrade Request',
                'verbose_name_plural': 'Membership Upgrade Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
